apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: hello
resources:
- ui.yaml
- configMap.yaml
vars:
- fieldref:
    fieldPath: metadata.name
  name: UI_LOCATION
  objref:
    apiVersion: v1
    kind: Service
    name: ui
configurations:
- config.yaml
