apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  kind: ui
resources:
- ui.yaml
- configMap.yaml
vars:
- fieldref:
    fieldPath: metadata.name
  name: UI_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: ui
- fieldref:
    fieldPath: metadata.namespace
  name: UI_NAMESPACE
  objref:
    apiVersion: v1
    kind: Service
    name: ui
configurations:
- config.yaml
