apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      deployment: hello-ui
  template:
    metadata:
      labels:
        deployment: hello-ui
    spec:
      containers:
      - name: ui
        image: ui
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: ui-config
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  selector:
    deployment: hello-ui
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
