apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: staging-
commonLabels:
  app: hello
  org: acmeCorporation
  variant: staging
commonAnnotations:
  note: Hello, I am staging!
resources:
- ../../../../base/api
- ../../../../base/ui
- ../../../../base/nginx
components:
- ../../components/auth
vars:
- fieldref:
    fieldPath: data.AUTH_API_HOSTNAME
  name: AUTH_API_HOSTNAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
- fieldref:
    fieldPath: data.JWT_AUTH_KEY
  name: JWT_AUTH_KEY
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
