apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  altGreeting: "Do you wonder, why a pineapple?"
  enableRisky: "true"
  # CREATE_NAMESPACE: wonder
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  MAIN_HOSTNAME: staging-hello-wonder.local
