apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-hello-blue-green
nameSuffix: -blue-green
commonAnnotations:
  note: Blue-Green at staging!
patchesJson6902:
- target:
    name: api
    kind: Deployment
    group: apps
    version: v1
  path: rename-to-rollout.yaml
configMapGenerator:
- files:
  - api.html
  name: api-content
- files:
  - ui.html
  name: ui-content
patchesStrategicMerge:
- api.yaml
- nginx.yaml
- ui.yaml
- ingress.yaml
- map.yaml
resources:
- ../base/hello
- preview-service.yaml
components:
- ../components/deployments/with-canary
configurations:
- config.yaml
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml