apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: staging-
commonLabels:
  org: acmeCorporation
  variant: staging
commonAnnotations:
  note: Hello, I am staging!
bases:
- ../../../../base/nginx
