apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          envFrom: null
          volumeMounts: null
      initContainers: null
      volumes: null