apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: staging-
nameSuffix: -central-config
namespace: staging-hello-central-config
commonLabels:
  app: hello
  org: acmeCorporation
  variant: staging
commonAnnotations:
  note: Hello, I am staging!
resources:
- ../../../base/central-config
components:
- ../components/central-config
images:
- name: central-config
  newName: nginx