apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: hello-api
  template:
    metadata:
      labels:
        deployment: hello-api
    spec:
      initContainers:
        - name: inject-databases
          image: alpine
          volumeMounts:
            - mountPath: /deployments
              name: config-template-volume
            - mountPath: /databases
              name: databases-volume
            - mountPath: /output
              name: app-deployments-volume
          command:
            - /bin/sh
            - -c
          args:
            - |
              apk add jq
              jq '.' -s /deployments/*.json >/tmp/_tmp_deployments.json
              jq 'add' -s /databases/*.json >/tmp/_tmp_databases.json
              cat /tmp/_tmp_deployments.json /tmp/_tmp_databases.json
              jq '.[1] as $databases | [.[0] | .[] | .DatabaseInfo.Server as $server | .DatabaseInfo *= ($databases | .[$server] // {})]' /tmp/_tmp_deployments.json /tmp/_tmp_databases.json >/output/deployments.json
      containers:
        - name: api
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: ALT_GREETING
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: altGreeting
            - name: ENABLE_RISKY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: enableRisky
          volumeMounts:
            - name: app-deployments-volume
              mountPath: /etc/deployments
      volumes:
        - name: app-deployments-volume
          emptyDir: {}
        - name: config-template-volume
          configMap:
            name: deployments
        - name: databases-volume
          secret:
            secretName: databases
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    deployment: hello-api
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
