apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  kind: api
resources:
- api.yaml
- configMap.yaml
- namespace.yaml
- sealedsecret_databases.json
vars:
- fieldref:
    fieldPath: metadata.name
  name: API_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: api
- fieldref:
    fieldPath: metadata.namespace
  name: API_NAMESPACE
  objref:
    apiVersion: v1
    kind: Service
    name: api
configMapGenerator:
- name: deployments
  files:
  - test_hello_dev_base.json
components:
- ../../components/databases/test
configurations:
- config.yaml
