apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: hello
resources:
- api.yaml
- configMap.yaml
- namespace.yaml
- sealedsecret_databases.json
vars:
- fieldref:
    fieldPath: data.CREATE_NAMESPACE
  name: CREATE_NAMESPACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
configMapGenerator:
- name: deployments
configurations:
- config.yaml
