apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
      - name: central-config
        image: central-config
        env:
        - name: JWT_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: JWT_CENTRAL_CONFIG_KEY
      - name: api
        $patch: delete
      initContainers: null
      volumes: null
