apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          image: central-config
          env:
            - name: JWT_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_CENTRAL_KEY
