apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: staging-
commonLabels:
  org: acmeCorporation
  variant: staging
commonAnnotations:
  note: Hello, I am staging!
patchesStrategicMerge:
- test_ss.json
- test3_ss.json
resources:
- ../../../../base/api
images:
- name: api
  newName: nginx