apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- to-try/test_dev_3_ss.json
- wonder/test3_dev2_ss.json
configMapGenerator:
- behavior: merge
  files:
  - to-try/test_dev_3.json
  - wonder/test3_dev2.json
  name: deployments
resources:
- hello
