apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
        - name: api
          image: auth
          env:
            - name: JWT_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_AUTH_KEY
            - name: CENTRAL_CONFIG_API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CENTRAL_CONFIG_API_URL
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api
spec:
  rules:
  - host: $(AUTH_API_HOSTNAME)
