apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      containers:
      - name: auth
        image: auth
        env:
        - name: JWT_KEY
          valueFrom:
            configMapKeyRef:
              key: JWT_AUTH_KEY
              name: app-config
        - name: CENTRAL_CONFIG_API_URL
          valueFrom:
            configMapKeyRef:
              key: CENTRAL_CONFIG_API_URL
              name: app-config
        - name: JWT_CENTRAL_CONFIG_KEY
          valueFrom:
            configMapKeyRef:
              key: JWT_CENTRAL_CONFIG_KEY
              name: app-config
      - name: api
        $patch: delete
      initContainers: null
      volumes: null
