apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kind: auth
patchesStrategicMerge:
- api.yaml
- configMap.yaml
resources:
- ../api
- ingress.yaml
vars:
- fieldref:
    fieldPath: data.CENTRAL_CONFIG_API_HOSTNAME
  name: CENTRAL_CONFIG_API_HOSTNAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
- fieldref:
    fieldPath: data.AUTH_API_HOSTNAME
  name: AUTH_API_HOSTNAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
configurations:
- config.yaml
components:
- ../../components/auth
- ../../components/central-config