apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  kind: application
commonLabels:
  app: hello
  org: acmeCorporation
namespace: hello
resources:
- ../api
- ../ui
- ../nginx
components:
- ../../components/auth
vars:
- fieldref:
    fieldPath: data.AUTH_API_HOSTNAME
  name: AUTH_API_HOSTNAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
- fieldref:
    fieldPath: data.JWT_AUTH_KEY
  name: JWT_AUTH_KEY
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config
