apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: production-
namespace: production-hello-auth
nameSuffix: -auth
commonLabels:
  app: hello
  org: acmeCorporation
  variant: production
commonAnnotations:
  note: Hello, I am production!
resources:
- ../../../base/auth
components:
- ../../../components/auth
- ../../../components/central-config
images:
- name: auth
  newName: nginx
