apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: staging-
namespace: staging-hello-auth
nameSuffix: -auth
commonLabels:
  app: hello
  org: acmeCorporation
  variant: staging
commonAnnotations:
  note: Hello, I am staging!
resources:
- ../../../base/auth
components:
- ../components/auth
- ../components/central-config
images:
- name: authImage
  newName: nginx