apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: null
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 5m # 5 minutes
      - setWeight: 20
      - pause: {} # pause indefinitely