apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-hello-canary
nameSuffix: -canary
commonAnnotations:
  note: Canary at staging!
patchesJson6902:
- target:
    name: api
    kind: Deployment
    group: apps
    version: v1
  path: rename-to-rollout.yaml
patchesStrategicMerge:
- api.yaml
- map.yaml
resources:
- ../base/hello
components:
- ../components/deployments/with-canary
configurations:
- config.yaml