apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-hello-canary
nameSuffix: -canary
commonAnnotations:
  note: Canary at staging!
# patchesStrategicMerge:
# - map.yaml
patchesJson6902:
  - target:
      name: api
      kind: Deployment
      group: apps
      version: v1
    path: rename-to-rollout.yaml
patchesStrategicMerge:
  - api.yaml
resources:
- ../base/hello
components:
- ../components/deployments/to-try
