apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: hello
resources:
- nginx.yaml
- configMap.yaml
vars:
- fieldref:
    fieldPath: data.MAIN_HOSTNAME
  name: MAIN_HOSTNAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: nginx-config
- fieldref:
    fieldPath: metadata.name
  name: API_LOCATION
  objref:
    apiVersion: v1
    kind: Service
    name: api
- fieldref:
    fieldPath: metadata.name
  name: UI_LOCATION
  objref:
    apiVersion: v1
    kind: Service
    name: ui
configurations:
- config.yaml
