apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  kind: nginx
resources:
- nginx.yaml
- configMap.yaml
vars:
- fieldref:
    fieldPath: data.MAIN_HOSTNAME
  name: MAIN_HOSTNAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: nginx-config
configurations:
- config.yaml
