apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      deployment: hello-nginx
  template:
    metadata:
      labels:
        deployment: hello-nginx
    spec:
      containers:
      - name: nginx
        image: nginxImage
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    deployment: hello-nginx
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    nginx.org/proxy-connect-timeout: "30s"
    nginx.org/proxy-read-timeout: "20s"
    nginx.org/client-max-body-size: "4m"
spec:
  rules:
  - host: $(MAIN_HOSTNAME)
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80