apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- behavior: replace
  files:
  - test3_dev2.json
  name: deployments
patchesStrategicMerge:
- map.yaml
resources:
- ../../base/api
