apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: hello-api
  template:
    metadata:
      labels:
        deployment: hello-api
    spec:
      initContainers:
        - name: inject-databases
          image: alpine
          envFrom:
            - secretRef:
                name: databases
          volumeMounts:
            - mountPath: /input
              name: config-template-volume
            - mountPath: /output
              name: app-deployments-volume
          command:
            - /bin/sh
            - -c
          args:
            - |
              apk add gettext jq
              jq '.' -s /input/*.json | envsubst >/output/deployments.json
      containers:
        - name: api
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: ALT_GREETING
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: altGreeting
            - name: ENABLE_RISKY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: enableRisky
          volumeMounts:
            - name: app-deployments-volume
              mountPath: /etc/deployments
      volumes:
        - name: app-deployments-volume
          emptyDir: {}
        - name: config-template-volume
          configMap:
            name: deployments
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    deployment: hello-api
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
