apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: hello
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      initContainers:
        - name: inject-databases
          image: alpine
          envFrom:
            - secretRef:
                name: databases
          volumeMounts:
            - mountPath: /input
              name: config-template-volume
            - mountPath: /output
              name: app-deployments-volume
          command:
            - /bin/sh
            - -c
          args:
            - |
              apk add gettext jq
              jq '.' -s /input/*.json | envsubst >/output/deployments.json
      containers:
        - name: the-container
          image: nginx
          ports:
            - containerPort: 8080
          env:
            - name: ALT_GREETING
              valueFrom:
                configMapKeyRef:
                  name: the-map
                  key: altGreeting
            - name: ENABLE_RISKY
              valueFrom:
                configMapKeyRef:
                  name: the-map
                  key: enableRisky
          volumeMounts:
            - name: app-deployments-volume
              mountPath: /etc/deployments
      volumes:
        - name: app-deployments-volume
          emptyDir: {}
        - name: config-template-volume
          configMap:
            name: deployments
