# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: hello

resources:
- api.yaml
- configMap.yaml
- namespace.yaml
- sealedsecret_databases.json

vars:
- fieldref:
    fieldPath: data.CREATE_NAMESPACE
  name: CREATE_NAMESPACE
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: app-config

configurations:
- config.yaml

configMapGenerator:
  - name: deployments
