apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: production-
namespace: production-hello
commonLabels:
  variant: production
commonAnnotations:
  note: Hello, I am production!
patchesStrategicMerge:
- deployment.yaml
- config.yaml
- large-db1_ss.json
- large-db2_ss.json
resources:
- ../../../base/hello
components:
- ../components/deployments/customer1
- ../components/deployments/customer2
images:
- name: api
  newName: nginx
- name: ui
  newName: nginx
