apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: production-
namespace: production-hello
commonLabels:
  app: hello
  org: acmeCorporation
  variant: production
commonAnnotations:
  note: Hello, I am production!
patchesStrategicMerge:
- reuseSecrets.yaml
- removeNamespace.yaml
resources:
- ../../../../base/producer
images:
- name: producer
  newName: nginx
