apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  template:
    spec:
      volumes:
      - name: databases-volume
        secret:
          secretName: production-databases
---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: databases
$patch: delete